branch-defaults:
  default:
    environment: instagram-filter
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udacityimageproject
  branch: null
  default_ec2_keyname: zion
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
